[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://impactcal-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/d/*"
  to = "https://impactcal-api.onrender.com/d/:splat"
  status = 200
  force = true
